import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/5OjjxZ9Zf773fkqv7inBEn/Simple-Library-test-for-Integration?node-id=2040-2223&t=M7xxaELFS2cwFumu-1",
  {
    props: {
      type: figma.enum("Type", {
        Primary: "primary",
        Secondary: "secondary",
        Tertiary: "tertiary",
      }),
      state: figma.enum("State", {
        Passive: "passive",
        Active: "active",
      }),
      action: figma.enum("Action", {
        Default: "default",
        Hover: "hover",
      }),
    },
    example: (props) => html`<scale-state-buttons />`,
  },
)
